In [45]:
import re
searchString = 'Wrox Professional guides are written by working developers to address everyday needs. My prof gets that!'

In [46]:
match = re.search('(Pro.*?des) are written by (wor.*?pers)', searchString)
print(match.group(0))
print(match.group(1))
print(match.group(2))

Professional guides are written by working developers
Professional guides
working developers


In [26]:
re.findall(pattern='g\w+', string=searchString)

['guides', 'gets']

In [47]:
re.findall(pattern='z\w+', string=searchString)

[]

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
print(iris.data[:5])
print(iris.target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [5]:
import pandas as pd
import numpy as np

In [49]:
raw_data = {'first_name': ['Jason Chan', 'Molly Pui', 'Tina Hui', 'Jake Duk', 'Amy K Chen'], 
        'last_name': ['Miller Heart Eche Coke', 'Jacobson Ache ache', 'Ali ache', 'Milner Arm Ache', 'Cooze Coke Cola'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70],
        'Sex': ['Female', 'Female', 'Female', 'Male', 'Male']}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore', 'Sex'])
df

first_name               last_name  age  preTestScore  postTestScore  \
0  Jason Chan  Miller Heart Eche Coke   42             4             25   
1   Molly Pui      Jacobson Ache ache   52            24             94   
2    Tina Hui                Ali ache   36            31             57   
3    Jake Duk         Milner Arm Ache   24             2             62   
4  Amy K Chen         Cooze Coke Cola   73             3             70   

      Sex  
0  Female  
1  Female  
2  Female  
3    Male  
4    Male

In [57]:
from pandas.api.types import CategoricalDtype

df['Sex2'] = df['Sex'].astype('category')
print(df['Sex2'].cat.codes)
print(df['Sex2'].cat.categories)

0    0
1    0
2    0
3    1
4    1
dtype: int8
Index(['Female', 'Male'], dtype='object')


In [22]:
# df.first_name.apply(str.lower)
# df.first_name.map(str.lower)
# df.first_name.map(lambda x: x.lower())
# df.first_name.map(lambda x: x.split(' ')[0])
df.first_name.str.split(' ').str.get(0)

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [11]:
i = 0
for lab, row in df.iteritems():
    print(lab)
    print(row)
    i += 1
    if i == 1:
        break 

first_name
0    Jason Chan
1     Molly Pui
2      Tina Hui
3      Jake Duk
4    Amy K Chen
Name: first_name, dtype: object


In [54]:
df.take([0,1], axis=1)

first_name               last_name
0  Jason Chan  Miller Heart Eche Coke
1   Molly Pui      Jacobson Ache ache
2    Tina Hui                Ali ache
3    Jake Duk         Milner Arm Ache
4  Amy K Chen         Cooze Coke Cola

In [84]:
df.last_name.str.extract('.*([A|E]che).*', flags=re.IGNORECASE, expand=False)

0    Eche
1    ache
2    ache
3    Ache
4     NaN
Name: last_name, dtype: object

In [84]:
df.last_name.str.extract('.*([A|E]che).*', flags=re.IGNORECASE, expand=False)

0    Eche
1    ache
2    ache
3    Ache
4     NaN
Name: last_name, dtype: object

In [52]:
df.last_name.str.endswith('ke')

0     True
1    False
2    False
3    False
4    False
Name: last_name, dtype: bool

In [53]:
df.last_name.str.match('A.*?e')

0    False
1    False
2     True
3    False
4    False
Name: last_name, dtype: bool

In [65]:
df.last_name.str.findall('A.*?e')

0            []
1        [Ache]
2    [Ali ache]
3    [Arm Ache]
4            []
Name: last_name, dtype: object

In [87]:
df.last_name.str.find('ache')

0    -1
1    14
2     4
3    -1
4    -1
Name: last_name, dtype: int64

In [82]:
df.last_name.str.contains('A.*?e')

0    False
1     True
2     True
3     True
4    False
Name: last_name, dtype: bool

In [98]:
df.last_name.str.find('ache').mode()

0   -1
dtype: int64

In [100]:
list(zip('abc', '123'))

[('a', '1'), ('b', '2'), ('c', '3')]

In [105]:
df.last_name.str.findall('A.*?e')

0            []
1        [Ache]
2    [Ali ache]
3    [Arm Ache]
4            []
Name: last_name, dtype: object

## Zip

In [104]:
[a + b + c for a, b, c in zip('abc', '123', 'efg')]

['a1e', 'b2f', 'c3g']

In [102]:
zip?

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(iter1 [,iter2 [...]]) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type
